name: PS5 System Update Tracker

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Test Sony server
        run: |
          python - <<'PY'
          import requests

          url = "http://fus01.ps5.update.playstation.net/update/ps5/official/tJMRE80IbXnE9YuG0jzTXgKEjIMoabr6/list/us/updatelist.xml"

          r = requests.get(url, timeout=20)

          print("HTTP STATUS:", r.status_code)
          print("CONTENT LENGTH:", len(r.content))
          print("FIRST 500 CHARACTERS:")
          print(r.text[:500])
          PY
